# Rules are applied to every window once it is created.
[[window_rules]]
command = "set title true"
match_process_name = ".*"

[[window_rules]]
command = "set rounded true"
match_process_name = ".*"

# Rules are applied to the focused window when the focus changes.
[[focused_window_rules]]
command = "set translucent 255"
match_process_name = ".*"

# Rules are applied to the unfocused windows when the focus changes.
[[unfocused_window_rules]]
command = "set translucent 220"
match_process_name = ".*"
